package atlas.view;

public enum SimEvent {
	
	ADD,
	EDIT,
	SPEED_CHANGED,
	SAVE,
	LOAD,
	MOUSE_CLICKED,
	MOUSE_DRAGGED,
	MOUSE_WHEEL_UP,
	MOUSE_WHEEL_DOWN,
	ESC,
	W, A, S, D,
	SPACEBAR_PRESSED,
	KEYBOARD_1, KEYBOARD_2, KEYBOARD_3, KEYBOARD_4,	KEYBOARD_5,
	KEYBOARD_6, KEYBOARD_7, KEYBOARD_8, KEYBOARD_9
}
