package atlas.view;

public enum SimEvent {
	
	ESC,	
	ADD,
	EDIT,
	MOUSE_CLICKED,
	MOUSE_DRAGGED,
	MOUSE_WHEEL_UP,
	MOUSE_WHEEL_DOWN,
	SPACEBAR_PRESSED,
	W, A, S, D,
	KEYBOARD_1, KEYBOARD_2, KEYBOARD_3, KEYBOARD_4,	KEYBOARD_5, 
	KEYBOARD_6, KEYBOARD_7, KEYBOARD_8, KEYBOARD_9
}
