package atlas.view;

public enum SimEvent {
	START,
	STOP,
	EXIT,
	ADD,
	EDIT,
	CENTER,
	LOCK,
	SPEED_CHANGED,
	NEWSIM,
	SAVE,
	LOAD,
	MOUSE_CLICKED,
	MOUSE_MULTI_CLICKED,
	MOUSE_PRESSED,
	MOUSE_DRAGGED,
	MOUSE_RELEASED,
	MOUSE_WHEEL_UP,
	MOUSE_WHEEL_DOWN,
	ESC,
	W, A, S, D,
	SPACEBAR_PRESSED,
	KEYBOARD_1, KEYBOARD_2, KEYBOARD_3, KEYBOARD_4,	KEYBOARD_5,
	KEYBOARD_6, KEYBOARD_7, KEYBOARD_8, KEYBOARD_9
}
